services:
  postgres:
    image: postgres:13
    container_name: postgres_dev
    environment:
      POSTGRES_DB: development_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  
